version: "3"
services:
    new_nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certbot/conf:/var/www/html
            - ./nginx:/etc/nginx/conf.d
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot:/var/www/html
        depends_on:
            - new_nginx
        # command: certonly --webroot --webroot-path=/var/www/html --email deejha927@gmail.com --agree-tos --no-eff-email --staging -d certiwise.io  -d www.certiwise.io