version: "3"
services:
    new_nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
            # - ./nginx:/etc/nginx/conf.d
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
        # command: certonly --webroot --webroot-path=/var/www/html --email deejha927@gmail.com --agree-tos --no-eff-email --staging -d certiwise.io  -d www.certiwise.io