FROM node:16.8.0-buster-slim as react-build

RUN apt-get update
WORKDIR /app
COPY package.json /app

RUN npm install --slient
COPY . /app
ARG REACT_APP_URL
ENV REACT_APP_URL=$REACT_APP_URL
RUN npm run build

FROM nginx
COPY --from=react-build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
CMD ["nginx", "-g", "daemon off;"]
